version: '3.9'

volumes:
  postgres-data:

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=postgres pg_isready -U postgres -h postgres"]
      interval: 10s
      timeout: 5s
      retries: 15

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_PORT: 5432
      DB_ADDR: ${KEYCLOAK_POSTGRES_HOST}
      DB_DATABASE: ${KEYCLOAK_DATABASE_NAME}
      DB_SCHEMA: ${KEYCLOAK_DATABASE_SCHEMA_NAME}
      DB_USER: ${KEYCLOAK_DATABASE_USERNAME}
      DB_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_IMPORT: "/opt/jboss/keycloak/imports/realm-test.json"
      KEYCLOAK_FRONTEND_URL: http://localhost:8080/auth
    volumes:
      - ./keycloak:/opt/jboss/keycloak/imports
    ports:
      - 0.0.0.0:8080:8080
    healthcheck:
      test: ["CMD-SHELL", "curl -s -I http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 15
    depends_on:
      postgres:
        condition: service_healthy

  gateway-service:
    image: ghcr.io/nkz-soft/gateway/gateway-service-api:latest
    container_name: gateway-service
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    ports:
      - 0.0.0.0:5000:80
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:80/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
    depends_on:
      keycloak:
        condition: service_healthy

  data-service:
    image: ghcr.io/nkz-soft/gateway/data-service-api:latest
    container_name: data-service
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    ports:
      - 0.0.0.0:5050:80
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:80/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
    depends_on:
      keycloak:
        condition: service_healthy
